[project]
site_name = "pizza_son"
site_description = "Documentation for the pizza_son Twitch bot"
site_url = "https://stumburs.github.io/pizza-son"
repo_url = "https://github.com/stumburs/pizza-son"
repo_name = "pizza-son"

nav = [
  { "Home" = "index.md" },
  { "Commands" = "commands.md" },
]

[project.theme]
name = "material"
language = "en"
features = [
  "navigation.instant",
  "navigation.top",
  "search.suggest",
  "search.highlight",
  "search.share",
]

[[project.theme.palette]]
scheme = "slate"
primary = "deep-purple"
accent = "purple"

[project.markdown_extensions.admonition]
[project.markdown_extensions.abbr]

[project.markdown_extensions.toc]
permalink = true

[project.search]
separator = '[\s\-\!]+'